# build environment
FROM node:8 as builder

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache react-scripts globally
RUN npm install react-scripts@1.1.1 -g --silent

# set working directory
WORKDIR /usr/src/app
RUN chown node:node /usr/src/app
RUN mkdir -p /usr/src/app/stats
RUN chown -R node:node /usr/src/app/stats
RUN chmod 755 /usr/src/app/stats

# Don't run stuff as root
USER node
RUN echo $UID

# install app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install --silent

# build our frontend assets
COPY . /usr/src/app

USER root
RUN chown -R node:node /usr/src/app/stats/
RUN chown -R node:node /usr/src/app/dist/
USER node

RUN ls -alh /usr/src/app/stats/

