version: '3.3'

services:
  db:
    image: postgres
  backend:
    build:
      context: ./backend
      args:
        mode: prod
    command: sh -c "python manage.py collectstatic --noinput; gunicorn config.wsgi:application --name dms --bind 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=global.settings.prod
    volumes:
      - ./backend:/code
      - stats:/code/stats
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
      - stats:/usr/src/app/stats
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/wp
  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile-prod
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend

volumes:
  stats:
