FROM python:3
ENV PYTHONUNBUFFERED 1

USER root

WORKDIR /code
ADD requirements/*.txt /code/requirements/
RUN pip install -r requirements/prod.txt
RUN pip install git+https://github.com/kevindice/django-allauth@c9c7522

RUN groupadd -r appuser -g 1000 \
    && useradd -u 1000 -r -g appuser -s /bin/false -c "App User" appuser \
    && chmod -R 755 /code

USER appuser

