FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code
ADD requirements/*.txt /code/requirements/
RUN pip install -r requirements/prod.txt
RUN pip install git+https://github.com/kevindice/django-allauth@c9c7522
ADD . /code/
EXPOSE 8000
CMD
