# Generated by Django 2.0.4 on 2018-06-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_view_full_profiles_of_others', 'Can view full profiles of others'),)},
        ),
    ]
