# Generated by Django 2.0.4 on 2018-09-20 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateInitiated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QD', 'queued'), ('DL', 'downloading'), ('DF', 'download failed'), ('UP', 'uploading'), ('UF', 'upload failed'), ('CP', 'complete')], default='QD', max_length=2)),
                ('fromPath', models.CharField(max_length=500)),
                ('toPath', models.CharField(max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.TransferBatch')),
            ],
        ),
    ]
