# Generated by Django 2.0.4 on 2018-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferbatch',
            name='hash',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
    ]
