# Generated by Django 2.0.4 on 2018-10-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_transferbatch_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transferfile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='transfer.TransferBatch'),
        ),
    ]
