# Generated by Django 2.0.8 on 2018-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20181010_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='retries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
