# Generated by Django 2.0.8 on 2018-11-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_auto_20181026_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='status',
            field=models.CharField(choices=[('PD', 'pending'), ('DL', 'downloading'), ('DF', 'download failed'), ('DS', 'download succeeded'), ('UP', 'uploading'), ('UF', 'upload failed'), ('US', 'upload succeeded'), ('CP', 'complete'), ('ED', 'expanding directory')], default='PD', max_length=2),
        ),
    ]
