import Button from 'react-bootstrap/lib/Button';
import Col from 'react-bootstrap/lib/Col';
import ControlLabel from 'react-bootstrap/lib/ControlLabel';
import Form from 'react-bootstrap/lib/Form';
import FormControl from 'react-bootstrap/lib/FormControl';
import FormGroup from 'react-bootstrap/lib/FormGroup';
import HelpBlock from 'react-bootstrap/lib/HelpBlock';
import React from 'react';

export default class AddSftpFileSystemForm extends React.Component {
  render () {
    return (
        <Form horizontal>
          <FormGroup controlId="systemId">
            <Col componentClass={ControlLabel} sm={3}>
              Id*
            </Col>
            <Col sm={9}>
              <FormControl type="text" />
              <HelpBlock>
                Id must be globally unique and cannot be reused once deleted.
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemName">
            <Col componentClass={ControlLabel} sm={3}>
              Name*
            </Col>
            <Col sm={9}>
              <FormControl type="text" />
              <HelpBlock>
                Common display name for this system
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemDescription">
            <Col componentClass={ControlLabel} sm={3}>
              Description
            </Col>
            <Col sm={9}>
              <FormControl componentClass="textarea"
                           placeholder="System Description (Optional)" />
              <HelpBlock>
                Verbose description of this system.  (Optional)
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemSite">
            <Col componentClass={ControlLabel} sm={3}>
              Site
            </Col>
            <Col sm={9}>
              <FormControl type="text" />
              <HelpBlock>
                Website URL associated with this system. (Optional)
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemHost">
            <Col componentClass={ControlLabel} sm={3}>
              Host URL*
            </Col>
            <Col sm={9}>
              <FormControl type="text" />
              <HelpBlock>
                Host URL for connecting via SSH/SFTP
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemPort">
            <Col componentClass={ControlLabel} sm={3}>
              Port Number*
            </Col>
            <Col sm={9}>
              <FormControl type="number" defaultValue={22} />
              <HelpBlock>
                Host Port for connecting via SSH/SFTP
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemUsername">
            <Col componentClass={ControlLabel} sm={3}>
              Username*
            </Col>
            <Col sm={9}>
              <FormControl type="text" />
            </Col>
          </FormGroup>

          <FormGroup controlId="systemPublicKey">
            <Col componentClass={ControlLabel} sm={3}>
              Public Key*
            </Col>
            <Col sm={9}>
              <FormControl componentClass="textarea"
                           placeholder="Public Key" />
              <HelpBlock>
                Public Key (generated by ssh-keygen).  Ensure this is added
                to your authorized_keys file in this system.
              </HelpBlock>
            </Col>
          </FormGroup>

          <FormGroup controlId="systemPrivateKey">
            <Col componentClass={ControlLabel} sm={3}>
              Private Key*
            </Col>
            <Col sm={9}>
              <FormControl componentClass="textarea"
                           placeholder="Private Key" />
              <HelpBlock>
                Private Key.  Don't share this one.
              </HelpBlock>
            </Col>
          </FormGroup>

          <div style={{
            textAlign: 'center'
          }}>
            <Button type="submit"
                    className="btn btn-success btn-fill">
              Add System
            </Button>
          </div>
        </Form>
    );
  }
}