# Generated by Django 2.0.4 on 2018-04-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20, verbose_name='method')),
                ('domain', models.CharField(max_length=100, verbose_name='domain')),
                ('port', models.PositiveSmallIntegerField(default=80)),
                ('path', models.CharField(max_length=250, verbose_name='path')),
                ('date', models.DateTimeField(auto_now=True)),
                ('querykey', models.CharField(editable=False, max_length=255, verbose_name='query key')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='RequestParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'GET'), ('P', 'POST')], default='G', max_length=1)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('value', models.CharField(blank=True, max_length=250, null=True, verbose_name='value')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='httpproxy.Request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'request parameter',
                'verbose_name_plural': 'request parameters',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=200)),
                ('content_type', models.CharField(max_length=200, verbose_name='content type')),
                ('content', models.TextField(verbose_name='content')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='httpproxy.Request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('method', 'domain', 'port', 'path', 'querykey')},
        ),
    ]
