export const ADD_FOCUSED_FILE = 'ADD_FOCUSED_FILE';
export const CLEAR_FOCUSED_FILES = 'CLEAR_FOCUSED_FILES';
export const SET_FOCUSED_FILE = 'SET_FOCUSED_FILE';
export const SET_FOCUSED_FILES_LIST = 'SET_FOCUSED_FILES_LIST';
export const REMOVE_FOCUSED_FILE = 'REMOVE_FOCUSED_FILED';
